### ISSUE TITLE
State param setting

### ISSUE THREAD

**Issue by zxlin** [jaredhanson/passport-twitter#102]
Twitter strategy is not accepting the state option to enable state param. I'm hoping to implement the state param to prevent CSRF. I'm creating the strategy as such, using `state: true`:

```JS
new TwitterStrategy({
  consumerKey,
  consumerSecret,
  state: true,
});
```

Am I missing something? I'm reading from @jaredhanson's comment in another repo that it should be as simple as that: https://github.com/jaredhanson/passport-google-oauth/pull/73#issuecomment-179019423

### Environment

* Operating System: Ubuntu 18.04
* Node version: 10.15.1
* passport version: 0.4.0
* passport-twitter version: 1.0.4

**Comment by jaredhanson** [comment]
Twitter uses OAuth 1.0, rather than OAuth 2.0.  OAuth 1.0 does not have an explicit `state` parameter.  CSRF protection is built-in, because a request token and secret is obtained and stored in the session prior to redirecting to Twitter.
