### ISSUE TITLE
creating a new application using passport-twitter and when using OAuth2.0 for authentication , unable to set website url for my project which is currently running at localhost, help me to fix this issue

### ISSUE THREAD

**Issue by abhijain2003** [jaredhanson/passport-twitter#111]
** READ THIS FIRST! **

#### Are you looking for help?

Reminder: The issue tracker is not a support forum.

Issues should only be filed in this project once they are able to be reproduced
and confirmed as a flaw in the software or incorrect information in associated
documention.

If you are encountering problems integrating this module into your application,
please post a question on the [discussion forum](https://github.com/passport/discuss)
rather than filing an issue.

#### Is this a security issue?

Do not open issues that might have security implications.  Potential security
vulnerabilities should be reported privately to jaredhanson@gmail.com.  Once any
vulerabilities have been repaired, the details will be disclosed publicly in a
responsible manner.  This also allows time for coordinating with affected parties
in order to mitigate negative consequences.

If neither of the above two scenarios apply to your situation, you should open
an issue.  Delete this paragraph and the text above, and fill in the information
requested below.

### Steps to reproduce

```js
// Format code using Markdown code blocks
```

### Environment

* Operating System: 
* Node version: 
* passport version: 
* passport-twitter version:

**Comment by jaredhanson** [comment]
Can you please provide more details.  For instance, where are you trying to set a website URL?  On Twitter's dashboard?  If so, that is unrelated to this particular strategy.  It's not clear from the title of the issue alone how this relates to `passport-twitter`, or how best to proceed.  Thanks.

**Comment by abhijain2003** [comment]
![Screenshot 2022-02-16 201856](https://user-images.githubusercontent.com/91718608/154290996-04c0b4b7-64ca-4a90-93de-34f8d8b77c36.png)
![Screenshot 2022-02-16 202011](https://user-images.githubusercontent.com/91718608/154291009-20053b46-29a5-490c-9c70-386d8d0fa553.png)
![Screenshot 2022-02-16 202103](https://user-images.githubusercontent.com/91718608/154291012-e0efbe06-7cd0-444e-84ff-c1cbda011166.png)
![Screenshot 2022-02-16 202125](https://user-images.githubusercontent.com/91718608/154291015-f219e040-6501-486c-aea1-5845a542f7ec.png)
![Screenshot 2022-02-16 202208](https://user-images.githubusercontent.com/91718608/154291020-754822b6-4597-4de3-8ed8-ae58312f0e95.png)
![Screenshot 2022-02-16 202245](https://user-images.githubusercontent.com/91718608/154291028-c04bfd32-4d26-465d-a704-e2838715a464.png)
![Screenshot 2022-02-16 202336](https://user-images.githubusercontent.com/91718608/154291031-61b958a0-f6c8-4bae-91db-1403918693a2.png)
![Screenshot 2022-02-16 202403](https://user-images.githubusercontent.com/91718608/154291033-922e151a-7a2e-4d2b-9993-54939cfa5282.png)
![Screenshot 2022-02-16 202429](https://user-images.githubusercontent.com/91718608/154291035-7e510e1c-566c-492d-b32c-0ba205bae296.png)

**Comment by abhijain2003** [comment]
I did all these, hope it'll helpful for you to detect problem

**Comment by jaredhanson** [comment]
This strategy uses OAuth 1.0a, not OAuth 2.0.  Enable and configure that in the user authentication settings, and it should work.  Let me know if that fixes it.

**Comment by abhijain2003** [comment]
![Screenshot 2022-02-17 125320](https://user-images.githubusercontent.com/91718608/154425645-0a913b36-c6ac-40b7-b0fe-b2ff10a540d2.png)

**Comment by abhijain2003** [comment]
unable to detect that error

**Comment by jaredhanson** [comment]
Is your callback URL on the same hostname/port as the route which redirects to Twitter?

**Comment by jaredhanson** [comment]
What I mean, is the hostname and port URL you start from needs to be the same.  ie, if you start on `localhost`, but the redirect is back to `127.0.0.1`, then the hostnames are different and sessions won't be restored correctly.  This would cause the error you are seeing.

**Comment by abhijain2003** [comment]
so should i use same on both places , ahh! let me try

**Comment by abhijain2003** [comment]
when i used 127.0.0.1:3000 for searching instead of localhost it's working thanks brother you helped me a lot🥳👍👨‍💻❤️
