### ISSUE TITLE
authenticationError: Unauthorized on Subdomain

### ISSUE THREAD

**Issue by VTFLAB** [jaredhanson/passport-twitter#113]
The problem is simple, is this a bug?  
if I set up a callback for this domain, you will be able to authenticate successfully.  
`https://example.com:3000/auth/twitter/callback ` 
  
But if you set it this way, the authentication will not pass.  
`https://sub.example.com/auth/twitter/callback`  
  
Error  
`AuthenticationError: Unauthorized`  
  
Doesn't Passport support authentication with subdomains?
Callback settings are already configured correctly in TwitterDevelop  
  
I would like to know if anyone is successfully using passport-twitter from a subdomain in the first place.

**Comment by jaredhanson** [comment]
"Unauthorized on Subdomain" is not an error that originates from Passport.  This suggests it is related to your application or its configuration.  Can you provide more details on the framework your app is using and how it is configured?  Stack traces would help pinpoint the issue.

**Comment by VTFLAB** [comment]
Thank you. Here's the stack trace.
```
[main_server] AuthenticationError: Unauthorized
[main_server]     at allFailed (/app/node_modules/passport/lib/middleware/authenticate.js:172:21)
[main_server]     at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:180:28)
[main_server]     at Strategy.strategy.fail (/app/node_modules/passport/lib/middleware/authenticate.js:302:9)
[main_server]     at verified (/app/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:150:36)
[main_server]     at Strategy._verify (/app/server.js:143:29)
[main_server]     at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
  execution environment
```
    "node": ">=14.16.1"
    "passport": "^0.4.1",
    "passport-glimesh": "^1.0.4",
    "passport-twitter": "^0.1.5",
```
  
It is running on Docker and uses ProxyPass to connect from the Nginx container to this application container  
  
Setting up around sessions  
```
let RedisStore = require("connect-redis")(session);
const ClusterOptions = {
  port: process.env.REDIS_PORT, // Redis port
  host: process.env.REDIS_HOST, // Redis host
  password: process.env.REDIS_PASS,
  retryStrategy: (times) => {
    // reconnect after
    return Math.min(times * 50, 2000);
  },
};
app.set("trust proxy", 1);
app.use(
  session({
    store: new RedisStore({ client: new Redis(ClusterOptions) }),
    secret: config.etc.cat,
    resave: true,
    saveUninitialized: true,
    cookie: {
      secure: "auto",
      maxAge: 2592000000,
    },
  })
);

app.use(passport.initialize());
app.use(passport.session());

passport.serializeUser(function (user, done) {
  try {
    done(null, user);
  } catch (error) {
    done(error);
  }
});

passport.deserializeUser(function (user, done) {
  try {
    done(null, user);
  } catch (error) {
    done(error);
  }
});
```
  
If there is other information needed, we will post it, but we cannot post the whole thing.

**Comment by VTFLAB** [comment]
I understood the problem, though I haven't solved it.
My frontend is something like example.com, but the backend is api.example.com
This was happening because the credentials were only in the example.com cookie and api.example.com could not get the credentials.
This will be a different issue, so I'll close it, thanks for the tip
