### ISSUE TITLE
error code 453, Elevated access

### ISSUE THREAD

**Issue by adrianotadao** [jaredhanson/passport-twitter#117]
Hey folks, do I really need to apply my project to Elevated level or could I do something else? Have you seen it before?

This is the error I'm getting:
```bash
APIError: You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve
  code: 453,
  status: 500
}
```

Thank you very much!

**Comment by kaushalkv** [comment]
I had a similar issue a few days back. I had to apply for Elevated access to the Twitter API, later it was working as expected.

**Comment by adrianotadao** [comment]
@kaushalkv same here. I will close it then. It seems that Elevated access is really required. Is there a plan to release a version that will support auth 2.0?
