### ISSUE TITLE
Is Twitter's change to paid API access change affecting Log In With Twitter functionality?

### ISSUE THREAD

**Issue by dmitrizzle** [jaredhanson/passport-twitter#119]
Context: https://twitter.com/twitterdev/status/1621026986784337922

I'm assuming that free access will be cut-off, but it's not clear at all whether that's true or not.

**Comment by jaredhanson** [comment]
This is a question that should be posed to Twitter.

**Comment by macduy** [comment]
My application was suspended recently, which broke sign ins using Twitter. The fix was to go to the developer portal and select a Tier. I chose the Free tier, which unsuspended my application and sign ins started working again

**Comment by dmitrizzle** [comment]
I did the same, but my application remained suspended (I had no problems with it for five years until now). My solution was to remove the Twitter sign-in and let users authenticate with the email they use with their bird accounts.
