### ISSUE TITLE
failed to obtain request token (Error: connect ETIMEDOUT)

### ISSUE THREAD

**Issue by khurrumqureshi** [jaredhanson/passport-twitter#23]
I am following the example but unable to get any success..

This is how i am setting my strategy
passport.use(new TwitterStrategy({
        consumerKey: TWITTER_CONSUMER_KEY,
        consumerSecret: TWITTER_CONSUMER_SECRET,
        callbackURL: "http://127.0.0.1:8080/auth/twitter/callback"
    },
    function(token, tokenSecret, profile, done) {
        // asynchronous verification, for effect...
        process.nextTick(function () {

```
        // To keep the example simple, the user's Twitter profile is returned to
        // represent the logged-in user.  In a typical application, you would want
        // to associate the Twitter account with a user record in your database,
        // and return that user instead.
        return done(null, profile);
    });
}
```

));

I have put the same callback url in my application setting on twitter
![twitter app](https://f.cloud.github.com/assets/1825659/5316/62ff04da-436a-11e2-9313-2e088f3275cb.jpg)

i am getting this error
failed to obtain request token (Error: connect ETIMEDOUT)
    at D:\Software Projects\botnik-server\node_modules\passport-twitter\node_modules\passport-oauth\lib\passport-oauth\strategies\oauth.js:184:36
    at D:\Software Projects\botnik-server\node_modules\passport-twitter\node_modules\passport-oauth\node_modules\oauth\lib\oauth.js:512:17
    at ClientRequest.<anonymous> (D:\Software Projects\botnik-server\node_modules\passport-twitter\node_modules\passport-oauth\node_modules\oauth\lib\oauth.js:391:7)
    at ClientRequest.emit (events.js:67:17)
    at CleartextStream.socketErrorListener (http.js:1188:9)
    at CleartextStream.emit (events.js:67:17)
    at Socket.onerror (tls.js:1146:17)
    at Socket.emit (events.js:88:20)
    at Array.0 (net.js:301:14)
    at EventEmitter._tickCallback (node.js:190:38)

**Comment by mattandrews** [comment]
@khurrumqureshi how did you fix this?
