### ISSUE TITLE
normalize provider params

### ISSUE THREAD

**Issue by dvv** [jaredhanson/passport-twitter#25]
Hi!

This one uses `consumerKey` and `consumerSecret` while most others `clientID` and `clientSecret`. I wonder if this could made to take also `clientID` and `clientSecret` (with some assignments done internally)?

TIA,
--Vladimir

**Comment by jaredhanson** [comment]
The options are named such as they are to match the protocols in use.  OAuth 1.0 refers to clients as "consumers".  OAuth 2.0 refers to them simply as "clients".  I think it is important as a developer to understand what protocols are in use by your application, if for no other reason than the security implications of such things.  Thus, the strategies force you to acknowledge this.  I don't have plans to abstract this away further.
