### ISSUE TITLE
Force Login

### ISSUE THREAD

**Issue by javieret** [jaredhanson/passport-twitter#34]
In the endpoint https://api.twitter.com/oauth/authenticate, it say that you can use the parameter force_login. How can I use this parameter with this library?

Thank you.

**Comment by Darkhogg** [comment]
For anyone reaching this issue trying to do this: Instead of editing the file, just pass `userAuthorizationURL: 'https://api.twitter.com/oauth/authenticate?force_login=true'` as an option to the strategy.
