### ISSUE TITLE
Add documentation for skipExtendedUserProfile option

### ISSUE THREAD

**Issue by kevinoid** [jaredhanson/passport-twitter#42]
I came across the `skipExtendedUserProfile` option in the code and it is great!  It makes the transition from Twitter back to the website much snappier for my use case.  Awesome!  I didn't see it in the documentation (`README.md` or passportjs.org), which is a shame since I'm guessing users are unaware and I think it would be appreciated.

Cheers,
Kevin

**Comment by jaredhanson** [comment]
Will take pull requests for more documentation.  Not a personal priority for me, closing.
