### ISSUE TITLE
does this Strategy require sessions?

### ISSUE THREAD

**Issue by davetayls** [jaredhanson/passport-twitter#43]
According to the Passport docs you should be able to disable sessions when authenticating like so:

```
passport.authenticate('twitter', {
  callbackURL: '...',
  session: false
});
```

When I do so I still get the following error:

`Error: OAuthStrategy requires session support. Did you forget app.use(express.session(...))?`

Is this something I'm missing or does this require sessions?

**Comment by benno208** [comment]
You could use passport.js like this:
[Token based, sessionless auth using express and passport]
(http://blog.jeroenpelgrims.be/token-based-sessionless-auth-using-express-and-passport/)

**Comment by benqus** [comment]
@Altiano yes, [here](https://github.com/jaredhanson/passport-twitter/blob/master/lib/strategy.js#L2) is the reason why

**Comment by alexandrepa** [comment]
Is there a way to use passport-twitter without a session ? Can I just enable passport session to fix this problem without interfering with passport JWT ?

**Comment by wizardnet972** [comment]
@jaredhanson so why `facebook-passport` doesn't need session?
