### ISSUE TITLE
{"errors":[{"message":"Could not authenticate you","code":32}]} error

### ISSUE THREAD

**Issue by skotchio** [jaredhanson/passport-twitter#50]
I've just started `passport-twitter` module in my new project and got the followng error when trying to authentificate via twitter account:

    {"errors":[{"message":"Could not authenticate you","code":32}]}

It's known issue and descrined here http://stackoverflow.com/questions/14672502/bug-or-spec-change-of-twitter-api-1-1 

Does anybody know how to fix this in passport-twitter ?

**Comment by sovanna** [comment]
why did you close this issue? had you find a solution?
