### ISSUE TITLE
oauth2

### ISSUE THREAD

**Issue by RWOverdijk** [jaredhanson/passport-twitter#57]
It looks like twitter [supports oauth2](https://dev.twitter.com/oauth/reference/post/oauth2/token) (I might be wrong).

My applications use jwt, and allow connecting via facebook, google plus and github, but not twitter. The reason for this is that passport-twitter uses oath 1.0 which requires a session.

Is it possible to update to 2.0?

**Comment by Maddis1337** [comment]
+1

**Comment by simison** [comment]
+11!

**Comment by hadokee** [comment]
+1

**Comment by sandro-pasquali** [comment]
Yes, non-session token auth support would be really great. Can't use twitter at this point.

**Comment by AlexKvazos** [comment]
+1

**Comment by Pencilbox** [comment]
+1

**Comment by diegoaguilar** [comment]
+1 This really should be updated already!

**Comment by radar155** [comment]
+1

**Comment by dguerra27** [comment]
+1

**Comment by craigspaeth** [comment]
+1

**Comment by merciba** [comment]
+1

**Comment by tzaitsev** [comment]
+1 Any status on this?

**Comment by simison** [comment]
Somene PR?

**Comment by simison** [comment]
https://www.bountysource.com/issues/9494113-oauth2

**Comment by kikar** [comment]
+1

**Comment by jaredhanson** [comment]
Twitter's OAuth 2.0 support only involved exchanging client credentials for an access token.  There's no user authentication performed during that process.  What is the use case for this functionality in a Passport strategy?

**Comment by jaredhanson** [comment]
Closing.  No use case for this functionality.
