### ISSUE TITLE
can we catch error responses on the request token?

### ISSUE THREAD

**Issue by jfromaniello** [jaredhanson/passport-twitter#62]
I see some errors like this on auth0 logs:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<hash>
  <error>Desktop applications only support the oauth_callback value 'oob'</error>
  <request>/oauth/request_token</request>
</hash>
```

It will be nice to decode this and use that error message instead.

**Comment by jaredhanson** [comment]
This is already implemented in the latest version, see here:
https://github.com/jaredhanson/passport-twitter/blob/master/lib/strategy.js#L179

We need to update both passport itself, as well as the strategies, in auth0.  There are a number of cleanups to error messages that we would get for free.

**Comment by jfromaniello** [comment]
awesome!
