### ISSUE TITLE
Error: This feature is temporarily unavailable

### ISSUE THREAD

**Issue by vimalcronj** [jaredhanson/passport-twitter#86]
when callback url is called it is showing that error and my application stuck in twitter page

Error: This feature is temporarily unavailable
    at Strategy.parseErrorResponse (/Users/cronj/Desktop/projects/slotuin/slotuin/slotuin-fullstack/node_modules/passport-twitter/lib/strategy.js:206:12)
    at Strategy.OAuthStrategy._createOAuthError (/Users/cronj/Desktop/projects/slotuin/slotuin/slotuin-fullstack/node_modules/passport-oauth1/lib/strategy.js:393:16)
    at /Users/cronj/Desktop/projects/slotuin/slotuin/slotuin-fullstack/node_modules/passport-oauth1/lib/strategy.js:154:43
    at /Users/cronj/Desktop/projects/slotuin/slotuin/slotuin-fullstack/node_modules/oauth/lib/oauth.js:465:22
    at passBackControl (/Users/cronj/Desktop/projects/slotuin/slotuin/slotuin-fullstack/node_modules/oauth/lib/oauth.js:397:13)
    at IncomingMessage.<anonymous> (/Users/cronj/Desktop/projects/slotuin/slotuin/slotuin-fullstack/node_modules/oauth/lib/oauth.js:409:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTGET /auth/twitter/callback?oauth_token=************************************

**Comment by all-bear** [comment]
The same is for me

**Comment by daraeman** [comment]
I'm also getting this error.

**Comment by cesarwbr** [comment]
Same error here

**Comment by sw-yx** [comment]
Can we get any help here? seems a common issue.

**Comment by wanderSX** [comment]
same here

**Comment by vimalcronj** [comment]
Actually conclusively i have solve that by changing my settings...there is no issue with twitter....check your code again...and twitter account setting with redirect url etc... all the best.. i know it's too annoying... :-p

**Comment by daraeman** [comment]
I did eventually fix this issue. Admittedly I can't remember how, but it isn't an issue with passport-twitter, its just an irrelevant error message.

**Comment by Asutosh989** [comment]
Mine also same error. @vimalcronj  and @daraeman can you please suggest some way to solve this?

**Comment by daraeman** [comment]
@Asutosh989 What's your repo/code. I'll compare it to mine.

**Comment by davodesign84** [comment]
Hi guys, I just stumbled on the same error. In my case it was due to the OPTIONS call preceding the POST. If you are using app.use('/route') try changing it to app.post

**Comment by GaelS** [comment]
I got the same error and it was caused by `done` function not being called in the callback created in the `TwitterStrategy` object.

**Comment by heyarviind** [comment]
Did anyone get the answer? Still stuck on same issue

**Comment by rahulraj7952** [comment]
In my case it was due to not setting a connection with mongoose

**Comment by Asutosh989** [comment]
@daraeman You can check my repo at [Twitter splitter](https://github.com/Asutosh989/twitter-splitter)

**Comment by jaker1** [comment]
Guys, those who face such problem, please, check whether you are not refreshing the page after your are beeing redirected to your callback.php file.
I fixed the problem by removing redirection to the same page.
Hope this helps!
