### ISSUE TITLE
Possible to get `referer` header?

### ISSUE THREAD

**Issue by cbosco** [jaredhanson/passport-twitter#88]
Hi, I have a qusetion about successful callback.

I'd like to do something like this:

```
app.get('/auth/twitter/callback', passport.authenticate('twitter'), (req, res) => {
  res.redirect(req.header('referer') || '/');
});
```

Which works with the facebook passport strategy but it seems as though Twitter strips this header. Do you happen to know if that's just how Twitter oauth behaves? Or is there a way to configure this strategy to do this?

Thanks

**Comment by kirya-pirat** [comment]
only over session
