### ISSUE TITLE
linking twitter with existing account

### ISSUE THREAD

**Issue by omryr** [jaredhanson/passport-twitter#89]
Hi I have a website with my own signup flows, I want to be able to link my accounts with twitter, the problem is, that once i call the flow routes.get('/auth/twitter/callback'... even if i were to pass an access token here i wouldn't be able to later deduct what it was since the next call goes to twitter and redirects, and is not transparent to me, is there a way to work around that?
(the sign up flow i am using isn't passport)

thanks for the help!

**Comment by scinos** [comment]
You should link the token from Twitter to your user in the strategy configuration

```
const strategy = new Strategy({
  consumerKey: TWITTER_CONSUMER_KEY,
  consumerSecret: TWITTER_CONSUMER_SECRET,
  callbackURL: "http://127.0.0.1:3000/auth/twitter/callback"

  // Pass the original request to your callback
  passReqToCallback: true
}, async (req, token, tokenSecret, profile, done) => {
  // Get your user form the original request. For example:
  const myUserId = req.user.id
  const user = await DB.User.findById(myUserId);

  // Update your user, for example in the DB
  await DB.User.update({
    twitterToken: token,
    twitterTokenSecret: tokenSecret,
    twitterUsername: profile.username,
  });
  done(null, user);  
});
```
