### ISSUE TITLE
Issue with example - "Failed to validate oauth signature and token"

### ISSUE THREAD

**Issue by colin-jack** [jaredhanson/passport-twitter#9]
I've been getting some odd behavior with twitter-passport so I decided to try the example, however when I run it and click the "Sign in with twitter" link I get the following error (regardless of whether I am already logged into twitter or not):

```
failed to obtain request token (status: 401 data: Failed to validate oauth signature and token)
    at /home/colin/Desktop/jaredhanson-passport-twitter-086ca27/examples/signin/node_modules/passport-twitter/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth.js:163:36
    at /home/colin/Desktop/jaredhanson-passport-twitter-086ca27/examples/signin/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:510:17
    at passBackControl (/home/colin/Desktop/jaredhanson-passport-twitter-086ca27/examples/signin/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:366:13)
    at IncomingMessage.<anonymous> (/home/colin/Desktop/jaredhanson-passport-twitter-086ca27/examples/signin/node_modules/passport-twitter/node_modules/passport-oauth/node_modules/oauth/lib/oauth.js:378:9)
    at IncomingMessage.emit (events.js:88:20)
    at HTTPParser.onMessageComplete (http.js:137:23)
    at CleartextStream.ondata (http.js:1124:24)
    at CleartextStream._push (tls.js:363:27)
    at SecurePair.cycle (tls.js:685:20)
    at EncryptedStream.write (tls.js:122:13)
```

**Comment by matijaabicic** [comment]
I'm having the same problem - i quadruple-checked my consumer key, secret and callback url, (127.0.0.1), my machine is synced to time.apple.com and still not working:

Error: Failed to validate oauth signature and token at Strategy.parseErrorResponse (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/lib/strategy.js:178:10) at Strategy.OAuthStrategy._createOAuthError (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:349:16) at /Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/lib/strategy.js:218:41 at /Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:543:17 at passBackControl (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:397:13) at IncomingMessage.<anonymous> (/Users/matijaabicic/work/Development/LicensePlate/node_modules/passport-twitter/node_modules/passport-oauth1/node_modules/oauth/lib/oauth.js:409:9) at IncomingMessage.EventEmitter.emit (events.js:117:20) at _stream_readable.js:920:16 at process._tickCallback (node.js:415:13)

**Comment by matijaabicic** [comment]
never mind, found my mistake. had my secret, key and callback variables inside quotation marks...which, of course made them not-variables
