### ISSUE TITLE
 How to use passport-twitter without using session

### ISSUE THREAD

**Issue by quocson1** [jaredhanson/passport-twitter#96]
Error: OAuth authentication requires session support. Did you forget to use express-session middleware?

Is there a way to fix without using session ????

**Comment by Adetona** [comment]
Have you installed the `express-session` package?

**Comment by kantharia** [comment]
@quocson1 - I am also getting the same error.  @Adetona - After installation `express-session` I am not getting that error.

**Comment by small-sunshines** [comment]
I have to use passport-twitter without session. Is there a way?

**Comment by akhoury** [comment]
need oauth1 requires a session we need oauth2 
https://github.com/jaredhanson/passport-twitter/issues/57

**Comment by delantai** [comment]
Also wondering about this.  It looks like the session is just used to store the OAuth request token -- I'm considering looking into using a custom session strategy that leverages a JWT token.  Would this be a bad idea @jaredhanson?  Feel like I must be overlooking something obvious...

**Comment by jaredhanson** [comment]
@delantai - Either way, you are going to end up with a cookie and a session.  If you are just trying to avoid a backend store, in order to be fully stateless, there are already solutions like [client-sessions](https://github.com/mozilla/node-client-sessions).  No need to roll your own with JWTs.

**Comment by delantai** [comment]
Oh perfect, thanks Jared.  Yep, was just to avoid setting up a session store for now.  Appreciate the quick response :-).

**Comment by raxityo** [comment]
Hey,

I have built several  restful APIs that don't want to add session support, so I am sharing the way I am using a simple `redis` store to store the `token:tokenSecret` pair. Unfortunately, it's undocumented how the store is supposed to be implemented (or I couldn't find any documentation out there), but it's pretty straightforward if you see the usage of the redis in `passport-oauth1`. Here is the redis store for example: https://gist.github.com/raxityo/f3872a4caeaa11f79921c3c252ceccc6

Our goal is to store the `token:tokenSecret` pair in some storage that can be retrieved later and it would be destroyed once the token has been used at step 3 above.

Hope it helps someone who runs into this situation.

**Comment by nick4fake** [comment]
https://twittercommunity.com/t/announcing-oauth-2-0-general-availability/163555
